version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Generate config
          command: |
            export GIT_COMMIT_MESSAGE="$(git log --format=%B -n 1 $CIRCLE_SHA1)"
            echo "GIT_COMMIT_MESSAGE='$GIT_COMMIT_MESSAGE'"
            yq -i ".parameters.commit_message.default = strenv(GIT_COMMIT_MESSAGE)" ./.circleci/main.yml
      - continuation/continue:
          configuration_path: ./.circleci/main.yml

workflows:
  setup:
    jobs:
      - setup